name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  PROJECT_FILE: ChromozoneSCP/ChromozoneSCP.csproj
    
jobs:
  build:
    runs-on: windows-latest
    
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'dhkatz/ChromozoneSCP'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3

#      - name: Setup Nuget
#        uses: iRebbok/setup-nuget@master

      - name: Install Dependencies
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: dotnet restore ${{ env.PROJECT_FILE }} --verbosity detailed
      
      - name: Build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: dotnet build ${{ env.PROJECT_FILE }} -c Release --no-restore
