name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REFERENCES_URL: https://exiled.host/build_deps/Dev.zip
  REFERENCES_PATH: ${{ github.workspace }}/References
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3

      - name: Install Dependencies
        run: nuget restore
        
      - name: Get References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile ${{ github.workspace }}/Dev.zip
          Expand-Archive -Path Dev.zip -DestinationPath ${{ env.REFERENCES_PATH }}
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          msbuild-architecture: x64
      
      - name: Build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild ChromozoneSCP\ChromozoneSCP.csproj -p:Configuration=Release -p:ReferencePath="${{ env.REFERENCES_PATH }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ChromzoneSCP
          path: "ChromozoneSCP/bin/Release/ChromozoneSCP.dll"
