name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  PROJECT_FILE: ChromozoneSCP/ChromozoneSCP.csproj
  PROJECT_BIN: ChhromozoneSCP/bin/Release
    
jobs:
  build:
    runs-on: windows-latest
    
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'dhkatz/ChromozoneSCP'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

#      - name: Setup Nuget
#        uses: iRebbok/setup-nuget@master

      - name: Install Dependencies
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: nuget restore ${{ env.PROJECT_FILE }}
      
      - name: Build
        working-directory: ${{ env.GITHUB_WORKSPACE }}
        run: msbuild ${{ env.PROJECT_FILE }} /m /p:Configuration=Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build Results
          path: ${{ env.PROJECT_BIN }}