name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'dhkatz/ChromozoneSCP'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        
      - name: Setup Nuget
        uses: iRebbok/setup-nuget@master
        
      - name: Install Dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
